"""empty message

Revision ID: 169a58724462
Revises: 190f00fac172
Create Date: 2022-06-21 16:13:03.324202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169a58724462'
down_revision = '190f00fac172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('post_id', sa.String(length=40), nullable=False))
    op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'])
    op.drop_column('likes', 'location_id')
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('likes', sa.Column('location_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'post_id')
    # ### end Alembic commands ###
