"""empty message

Revision ID: 190f00fac172
Revises: 81eee9aba419
Create Date: 2022-06-21 15:42:36.832095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190f00fac172'
down_revision = '81eee9aba419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('comments', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comments')
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###
