"""empty message

Revision ID: 425341de8ea8
Revises: 73b1182ccba9
Create Date: 2022-06-21 21:30:26.737986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425341de8ea8'
down_revision = '73b1182ccba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_username_fkey', 'likes', type_='foreignkey')
    op.drop_column('likes', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key('likes_username_fkey', 'likes', 'user', ['username'], ['id'])
    # ### end Alembic commands ###
