"""empty message

Revision ID: 474392009131
Revises: cda92f6b4512
Create Date: 2022-06-21 12:01:51.072939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474392009131'
down_revision = 'cda92f6b4512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('location_id', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'location_id')
    # ### end Alembic commands ###
