"""empty message

Revision ID: 610944e6017d
Revises: dd546dd2a015
Create Date: 2022-06-12 13:13:14.754950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610944e6017d'
down_revision = 'dd546dd2a015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('preview', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid')
    # ### end Alembic commands ###
