"""empty message

Revision ID: 61e5aae7d63f
Revises: 474392009131
Create Date: 2022-06-21 12:32:20.954670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e5aae7d63f'
down_revision = '474392009131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
