"""empty message

Revision ID: 73b1182ccba9
Revises: ec4a2ffee894
Create Date: 2022-06-21 21:23:36.520075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b1182ccba9'
down_revision = 'ec4a2ffee894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('username', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'likes', 'user', ['username'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'username')
    # ### end Alembic commands ###
