"""empty message

Revision ID: 7ea29cde2250
Revises: c582a6cf570e
Create Date: 2022-06-22 09:05:13.965107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea29cde2250'
down_revision = 'c582a6cf570e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
