"""empty message

Revision ID: 81eee9aba419
Revises: 61e5aae7d63f
Create Date: 2022-06-21 13:22:32.933123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81eee9aba419'
down_revision = '61e5aae7d63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'user_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'user_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
