"""empty message

Revision ID: 83b03c1a13a8
Revises: 920f95d81023
Create Date: 2022-06-18 00:25:15.949412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b03c1a13a8'
down_revision = '920f95d81023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid', sa.Column('track_img', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid', 'track_img')
    # ### end Alembic commands ###
