"""empty message

Revision ID: 8bec5e38215e
Revises: bf5c2fe322a2
Create Date: 2022-06-17 14:04:34.509501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bec5e38215e'
down_revision = 'bf5c2fe322a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grid', 'artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('grid', 'track',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('grid', 'preview',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grid', 'preview',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('grid', 'track',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('grid', 'artist',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
