"""empty message

Revision ID: 920f95d81023
Revises: e2b7808b6b29
Create Date: 2022-06-18 00:23:38.057276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920f95d81023'
down_revision = 'e2b7808b6b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid', sa.Column('track_img', sa.String(length=225), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid', 'track_img')
    # ### end Alembic commands ###
