"""empty message

Revision ID: e2b7808b6b29
Revises: e8fff5fc44f7
Create Date: 2022-06-18 00:21:31.650946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b7808b6b29'
down_revision = 'e8fff5fc44f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid', 'preview')
    op.drop_column('grid', 'track_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid', sa.Column('track_img', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('grid', sa.Column('preview', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
