"""empty message

Revision ID: e8fff5fc44f7
Revises: 8bec5e38215e
Create Date: 2022-06-17 14:07:24.600176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fff5fc44f7'
down_revision = '8bec5e38215e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid', sa.Column('grid_position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid', 'grid_position')
    # ### end Alembic commands ###
