"""empty message

Revision ID: ec4a2ffee894
Revises: 4be94cb1aa95
Create Date: 2022-06-21 18:48:38.315806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4a2ffee894'
down_revision = '4be94cb1aa95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_likes_timestamp'), 'likes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_timestamp'), table_name='likes')
    op.drop_column('likes', 'timestamp')
    # ### end Alembic commands ###
